version: "1"
services:
  social-network-analyzer:
    build: .
    ports:
      - "5006:5006"
    volumes:
      - ./src:/app
    environment:
      - REDDIT_CLIENT_KEY=${REDDIT_CLIENT_KEY}
      - REDDIT_CLIENT_SECRET=${REDDIT_CLIENT_SECRET}
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}